### ISSUE TITLE
Kevoree js and CentralizedWSGroup

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-js#46]
Hi I tried to update my kev script for using the new CentralizedWSGroup but i get an error both in desktop and docker environment

15:58:16 Core            Deploy process started...
15:58:16 Core            Start 'node0' bootstrapping...
15:58:16 NPMResolver     kevoree-node-javascript@5.4.0-beta.3 found in C:\Users\TDalianis\.kevoree (48ms)
15:58:16 Core            Set default node param: logLevel=INFO
15:58:16 Core            Error: no DeployUnit found for 'sync: CentralizedWSGroup/2' that matches the 'js' platform
  at Object.processTrace (C:\Users\TDalianis\.kevoree\node_modules\kevoree-node-javascript\lib\AdaptationEngine.js:164:31)
  at Object.<anonymous> (C:\Users\TDalianis\.kevoree\node_modules\kevoree-node-javascript\lib\AdaptationEngine.js:95:12)
  at Array.forEach (native)
  at Object.processTraces (C:\Users\TDalianis\.kevoree\node_modules\kevoree-node-javascript\lib\AdaptationEngine.js:94:26)
  at PseudoClass.processTraces (C:\Users\TDalianis\.kevoree\node_modules\kevoree-node-javascript\lib\JavascriptNode.js:80:34)
  at C:\Users\TDalianis\workspace_heads\streamvisualiser\node_modules\kevoree-core\kevoree-core.js:161:41
  at C:\Users\TDalianis\workspace_heads\streamvisualiser\node_modules\kevoree-core\kevoree-core.js:422:6
  at C:\Users\TDalianis\workspace_heads\streamvisualiser\node_modules\kevoree-commons\lib\Bootstrapper.js:71:9
  at NPMResolver.loadClass (C:\Users\TDalianis\workspace_heads\streamvisualiser\node_modules\kevoree-resolvers\lib\NPMResolver.js:140:2)
  at NPMResolver.<anonymous> (C:\Users\TDalianis\workspace_heads\streamvisualiser\node_modules\kevoree-resolvers\lib\NPMResolver.js:94:10)
  at C:\Users\TDalianis\workspace_heads\streamvisualiser\node_modules\kevoree-resolvers\lib\exists.js:84:5
  at tryToString (fs.js:455:3)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

Fatal error: Cannot read property 'map' of undefined

Any ideas?

**Comment by brice-morin** [comment]
In your kevscript, try to use /1/LATEST for the CentralizedWSGroup instead of (I guess) /LATEST/LATEST and see if it helps. It is actually no version /2/LATEST for the JS version and, for some reasons, /LATEST/LATEST will resolve to /2/LATEST as it exists such a version for Java but not for JS...

**Comment by tdalianis** [comment]
Yeap, that did the trick.

Thanks

**Comment by tdalianis** [comment]
I am afraid the javascript version also needs an update. I am running the "streamvisualiser" project and It throws an error

11:32:21 Core            TypeError: Cannot read property 'metaClassName' of null
    at isInstance (/root/.kevoree/node_modules/kevoree-node-javascript/lib/AdaptationEngine.js:39:11)
    at Object.isVirtual (/root/.kevoree/node_modules/kevoree-node-javascript/lib/AdaptationEngine.js:568:9)
    at Object.isVirtual (/root/.kevoree/node_modules/kevoree-node-javascript/lib/AdaptationEngine.js:569:19)
    at Object.processTrace (/root/.kevoree/node_modules/kevoree-node-javascript/lib/AdaptationEngine.js:149:17)
    at Object.<anonymous> (/root/.kevoree/node_modules/kevoree-node-javascript/lib/AdaptationEngine.js:95:12)
    at Array.forEach (native)
    at Object.processTraces (/root/.kevoree/node_modules/kevoree-node-javascript/lib/AdaptationEngine.js:94:26)
    at PseudoClass.processTraces (/root/.kevoree/node_modules/kevoree-node-javascript/lib/JavascriptNode.js:80:34)
    at /usr/lib/node_modules/kevoree-cli/node_modules/kevoree-core/kevoree-core.js:161:41
    at KevoreeCore.checkBootstrapNode (/usr/lib/node_modules/kevoree-cli/node_modules/kevoree-core/kevoree-core.js:427:4)
/usr/lib/node_modules/kevoree-cli/node_modules/kevoree-core/kevoree-core.js:170
                                                                .map(function (cmd) {
                                                                ^

TypeError: Cannot read property 'map' of undefined
    at /usr/lib/node_modules/kevoree-cli/node_modules/kevoree-core/kevoree-core.js:170:9
    at KevoreeCore.checkBootstrapNode (/usr/lib/node_modules/kevoree-cli/node_modules/kevoree-core/kevoree-core.js:427:4)
    at KevoreeCore.deploy (/usr/lib/node_modules/kevoree-cli/node_modules/kevoree-core/kevoree-core.js:142:10)
    at register (/root/.kevoree/node_modules/kevoree-group-centralizedws/lib/client/push.js:21:28)
    at Object.client.onmessage (/root/.kevoree/node_modules/kevoree-group-centralizedws/lib/client/index.js:55:7)
    at WebSocket.client.onmessage (/root/.kevoree/node_modules/rwebsocket/rwebsocket.js:25:9)
    at WebSocket.onMessage (/root/.kevoree/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/root/.kevoree/node_modules/ws/lib/WebSocket.js:841:10)

**Comment by maxleiko** [comment]
Just release updated versions of the CentralizedWSGroup/2 both in Java and JavaScript.

If you want to play with it in a cross-platform way, here's a KevScript starting point:

```kevs
add master: JavascriptNode/LATEST/LATEST
add client: JavaNode/LATEST/LATEST
add sync: CentralizedWSGroup/LATEST/LATEST

attach * sync

set sync.isMaster/master = 'true'
set sync.masterNet/client = 'ip.lo'

network master.ip.lo 127.0.0.1
```

Then open 2 terminals.
In the first one:

`kevoree start -m /tmp/main.kevs -n master`

And in the second one:

`java -Dnode.bootstrap=/tmp/main.kevs -Dnode.name=client -jar Programs/kevoree/bin/runtime.jar | klogs`


NB:
Remember to update your kevoree-cli with `npm i -g kevoree-cli`
If you want to have pretty logs in Java you can install [klogs](https://github.com/kevoree/klogs) (there is the documentation on how to use it, but basically it's just a pipe..)
